%dw 2.0
output application/json
---
{
    Message: {
        Subject: "FORMAT-WUP: Dual BOM detected for item " ++ (vars.articleItem.item[0].item_id default ""),
        Body: {
            ContentType: "Text",
            Content: 
                "Dual BOM detected for item " ++ (vars.articleItem.item[0].item_id default "") ++ "\n" ++
                "Item description: " ++ (vars.articleItem.item[0].item_description default "") ++ "\n" ++
                "Item number: " ++ (vars.articleItem.item[0].item_number default "") ++ "\n" ++
                "Selected org: " ++ (vars.orgToUse default "") ++ "\n" ++
                "Timestamp: " ++ (now() as String {format: "uuuu-MM-dd HH:mm"}) ++ "\n\n" ++
                "This is an automated alert generated by FORMAT-WUP integration."
        },
        ToRecipients: [
            {
                EmailAddress: {
                    Address: p('m365.emailTest')
                }
            }
        ]
    },
    SaveToSentItems: false
}